- name: Build and Deploy On ENV STG
  hosts: ubuntu
    #become_method: sudo
  gather_facts: yes
  remote_user: ubuntu
  vars:
    BRANCH_NAME: "master"
  tasks:
      - name: Build-Deploy
        shell: |
            "/home/ubuntu/deploy/deploy.sh "" {{BRANCH_NAME}} "
    
        register: command_output
      - debug: var=command_output.stdout_lines
