- name: Build and Deploy On ENV STG
  hosts: ubuntu
    #become_method: sudo
  gather_facts: yes
  remote_user: ubuntu
  var:
     DEPLOYMENT_ENV: "origin/master"
  tasks:
      - name: Build-Deploy
        shell: |
            /home/ubuntu/deploy/deploy.sh DEPLOYMENT_ENV
        register: DEPLOYMENT_ENV
      - debug: var=DEPLOYMENT_ENV.stdout_lines

