- name: Build and Deploy On ENV STG
  hosts: ubuntu
  gather_facts: yes
  args:
    executable: /bin/bash
  remote_user: ubuntu
  vars:
    DEPLOYMENT_ENV: "origin/master"
    BRANCH_NAME: "master"
  tasks:
      - name: Build-Deploy
        shell: |
            "/home/ubuntu/deploy/deploy.sh "
    
        register: command_output
      - debug: var=DEPLOYMENT_ENV
